language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS=28

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-$ANDROID_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS

script:
    - ./gradlew clean test build